version: "3.9"
services:
   php-apache:
     container_name: php
     ports:
       - "80:80"
     build: 
       context: .
       dockerfile: Dockerfile_php
     volumes:
       - ./index.php:/var/www/html/index.php  
     depends_on:
      - mysql

   mysql:
     container_name: mysql 
     ports: 
       - "3306:3306"
     build: 
       context: .
       dockerfile: Dockerfile_mysql
     environment:
       MYSQL_ROOT_PASSWORD: "super-secret-password" 
       MYSQL_DATABASE: "my-database"
       MYSQL_USER: "my-user"
       MYSQL_PASSWORD: "my-password"
     volumes:
        - ./Docker2:/var/lib/mysql 
   redis:
    container_name: redis
    restart: always
    ports:
     - 6379:6379 
    build: 
       context: .
       dockerfile: Dockerfile_redis
   nginx:
    image: nginx:latest
    ports: 
     - 8081:80
    volumes: 
     - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - php-apache




